url: https://uranmaj.com
baseurl: ""

title: Maj Uran
description: Web + mobile developer / designer
image: /assets/images/majuran.webp

nav:
  - title: Maj Uran
    url: /
  - title: Case studies
    url: /case-studies
  - title: CV
    url: /cv

collections:
  case-studies:
    output: true
    permalink: /case-studies/:name/
