title: Maj Uran
email: email
description: Personal portfolio
baseurl: ""
url: ""
github_username: uranmaj

nav:
  - title: Maj Uran
    url: /
  - title: Case studies
    url: /case-studies
  - title: CV
    url: /cv
  - title: Contact
    url: /contact

collections:
  case-studies:
    output: true
    permalink: /case-studies/:name/
